#!/usr/bin/python3
def raise_exception():
    a = "hello"
    b = 5
    c = a + b
